// Generated by build-photos.mjs — do not edit by hand.
// Re-run `node build-photos.mjs` after adding or removing photos.
window.REAL_PHOTOS = {
  "travel": [
    {
      "sets": [
        {
          "src": "photos/travel/01-banff/-1.jpg",
          "w": 2048,
          "h": 1365,
          "t": "Banff"
        },
        {
          "src": "photos/travel/01-banff/-2.jpg",
          "w": 2048,
          "h": 1365,
          "t": "Banff"
        },
        {
          "src": "photos/travel/01-banff/-3.jpg",
          "w": 1447,
          "h": 2048,
          "t": "Banff"
        },
        {
          "src": "photos/travel/01-banff/-4.jpg",
          "w": 1524,
          "h": 2048,
          "t": "Banff"
        },
        {
          "src": "photos/travel/01-banff/-5.jpg",
          "w": 1365,
          "h": 2048,
          "t": "Banff"
        },
        {
          "src": "photos/travel/01-banff/-6.jpg",
          "w": 2048,
          "h": 1365,
          "t": "Banff"
        }
      ]
    },
    {
      "sets": [
        {
          "src": "photos/travel/02-china spring 2026/-01.jpg",
          "w": 2048,
          "h": 1365,
          "t": "China Spring 2026"
        },
        {
          "src": "photos/travel/02-china spring 2026/-02.jpg",
          "w": 2048,
          "h": 1365,
          "t": "China Spring 2026"
        },
        {
          "src": "photos/travel/02-china spring 2026/-03.jpg",
          "w": 2048,
          "h": 1365,
          "t": "China Spring 2026"
        },
        {
          "src": "photos/travel/02-china spring 2026/-04.jpg",
          "w": 1448,
          "h": 2048,
          "t": "China Spring 2026"
        },
        {
          "src": "photos/travel/02-china spring 2026/-05.jpg",
          "w": 1762,
          "h": 2048,
          "t": "China Spring 2026"
        },
        {
          "src": "photos/travel/02-china spring 2026/-06.jpg",
          "w": 2048,
          "h": 1365,
          "t": "China Spring 2026"
        },
        {
          "src": "photos/travel/02-china spring 2026/-07.jpg",
          "w": 1437,
          "h": 2048,
          "t": "China Spring 2026"
        },
        {
          "src": "photos/travel/02-china spring 2026/-08.jpg",
          "w": 1448,
          "h": 2048,
          "t": "China Spring 2026"
        },
        {
          "src": "photos/travel/02-china spring 2026/-09.jpg",
          "w": 1485,
          "h": 2048,
          "t": "China Spring 2026"
        },
        {
          "src": "photos/travel/02-china spring 2026/-10.jpg",
          "w": 1462,
          "h": 2048,
          "t": "China Spring 2026"
        }
      ]
    }
  ],
  "personal": [],
  "bruin": []
};
